### ISSUE TITLE
Kodi exit fullscreen with steam big picture launcher.

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#10]
Hi when I launch steam big picture from advanced emulator launcher kodi exit the fullscreen even if I set the minimize kodi option to off.

**Comment by Wintermute0110** [comment]
I can confirm this bug. Will fix ASAP.

**Comment by Wintermute0110** [comment]
For some reason this seems to work now! I saw this behaviour in my HTPC but when I tested AEL in my Debian laptop I couldn’t reproduce the bug!

Anyway, I have put some logging messages in the code to help catching the bug if still present. Please try last committed version of AEL and tell me the results.

**Comment by mac1202** [comment]
Bug still present log here : http://pastebin.com/yBLm5rn5

**Comment by Wintermute0110** [comment]
Sorry, forgot about standalone launcher! Will fix ASAP.

**Comment by mac1202** [comment]
I try with every launcher i have, confim that the bug is fixed.
