### ISSUE TITLE
add http://www.arcadehits.net scraper

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#12]
Hi on advanced launcher it was the only scraper to properly scrape info for mame rom. Are you planning to reintroduce it in AEL ?

**Comment by Wintermute0110** [comment]
Hi, AEL already incorporates a custom MAME offline scraper will all metadata (including category from Catver.ini) expect plot. Needless to say, the offline metadata scraper is much much faster than the online one.

Please have a try. Make sure you correctly select 'MAME' as the platform when creating the launcher. All the MAME ROMs will have correct name and metadata.

**Comment by Wintermute0110** [comment]
Will close the issue now. Reopen if you find problems.
