### ISSUE TITLE
[Feature Request] Add to Favorites

### ISSUE THREAD

**Issue by eggfoo** [Wintermute0110/plugin.program.advanced.emulator.launcher#23]
Was removed in latest build.
Currently when I enter into AEL. the 3 options that I have are:

[Rom collections] _(cant remove)_
Favorites _(cant remove)_
Emulators _(my folder with all my emulators)_

I would LOVE to have the ability to add the folder "Emulators" back to Favorites.
So that I may add that Favorites link to my homepage. So I can launch directly there, without having to select "Emulators" 1st. 

Its like having an Index.Html page with a link saying "click here to enter" that directs you to home.html
Extra step Id like to skip

Thank you

**Comment by Wintermute0110** [comment]
I do not understand what you mean, can you explain in a better way (like putting an example of how the root window of the addon should look like)?

**Comment by eggfoo** [comment]
Sure thing. I'll post a video of what I mean when I get home in approx 12hrs from time of posting

**Comment by eggfoo** [comment]
http://i.imgur.com/FnEFpnE.jpg
Addons (context menu)

http://i.imgur.com/97BhbgC.jpg
AEL (context menu)

http://i.imgur.com/xeW41GH.jpg
My selected category (context menu)


So I can add AEL to my favorites via the context menu of Addons.
But I can not add any Category within AEL as a favorite. 

So in order to access my Emulators. I have to:
Addons > AEL Addon > AEL Category > Emulator.

I can add AEL to favorites. So then the process would be:
Favorite option: AEL Addon > AEL Category > Emulator

Id rather:
Favorite option: AEL Category > Emulator

So when selecting the Favorite option of "AEL Category" it launches directly inside. Then i can select the Emulator i want.

This was an available option in Adv Launcher.


Hope that makes Some?/ Any? sense to you

**Comment by Wintermute0110** [comment]
@eggfoo I think your problem will be solved in Krypton. In Jarvis, I disabled the default Kodi menu and it is the default Kodi menu that allows you to put stuff into Kodi Favourites. I disabled the menu because the context menu was too much overloaded in some contexts.

In Krypton, however, you cannot disable the context menu (although the default menu has been improved) so you can add any Category/Launcher/ROM to Kodi favourites. Please try Krypton Beta 2 and tell me the results.

**Comment by eggfoo** [comment]
Makes sense. I'll download krypton beta2 and test it in a test environment and report back

**Comment by eggfoo** [comment]
Resolved with krypton
