### ISSUE TITLE
Problem scraping Wii Sports from theGameDB

### ISSUE THREAD

**Issue by smoothquark** [Wintermute0110/plugin.program.advanced.emulator.launcher#30]
Hi! Thanks for your great work. Have come across an issue, though...

When scraping "Wii Sports", I get "Wii Sports and Wii Sports Resort" instead. Looks like the api function (http://thegamesdb.net/api/GetGamesList.php?name=Wii%20Sports) does not return "Wii Sports". To get "Wii Sports", I need (http://thegamesdb.net/api/GetGame.php?exactname=Wii%20Sports). Is it possible to have "exact matching" as an option? Thanks.

**Comment by Wintermute0110** [comment]
Hi. I guess you have this problem when using the ROM scanner, right? If you scrape the ROM using the context menu you see the list of games returned, the exact match is in the second position?

**Comment by smoothquark** [comment]
The second position is "Wii Sports Resort". "Wii Sports" does not appear at all using the thegamesdb API other than GetGame.php with an exactname. I presume this is entirely due to thegamesdb API and not your scraper. Just wondering - is it possible to include gametdb (http://www.gametdb.com/) as a metadata source? They seem to be more complete for Wii games.

**Comment by Wintermute0110** [comment]
OK, looks like a bug in TheGamesDB. Will add some setting for exact matches for 0.9.6. As a general policy, I do not want to make a scraper of a site just for a bunch of platforms (with the exception of MAME). Can you scrape the game metadata with GameFAQs and/or MobyGames? Also, if possible please contact TheGamesDB people and report this bug.

**Comment by smoothquark** [comment]
Ok. Thanks. I think I am going to stick to nfo for now. GameTDB has good metadata but lousy covers.
