### ISSUE TITLE
Scanning ROMs with Asset Scan Policy set to Local Files does not pull in images

### ISSUE THREAD

**Issue by smoothquark** [Wintermute0110/plugin.program.advanced.emulator.launcher#32]
Hi again. I think I have discovered another bug...

When scanning ROMs and "Asset scan policy" set to "Local Files", local files are not pulled in. I seem to have isolated the problem down to line 240 in utils.py:

`file_path = rootPath + filename_noext + '.' + ext`

The file-path that is generated from the above line gives: "rootPath/filename_noext/./ext" rather than "rootPath/filename_noext.ext". This correction seems to work:

`file_path = rootPath.join(filename_noext + '.' + ext)`

**Comment by Wintermute0110** [comment]
Thanks again, will fix ASAP.

**Comment by Wintermute0110** [comment]
Hi. I think this issue has been solved. I will close it now.
