### ISSUE TITLE
Unable to open category after updating to git version

### ISSUE THREAD

**Issue by fx02** [Wintermute0110/plugin.program.advanced.emulator.launcher#35]
20:06:03.956 T:2232   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=a34da3225f7c4d50662dd6d5ea9383de&com=SHOW_ROMS&launID=693daf14ff92c7f6e9b5801f18fa4bb1
20:06:03.956 T:2232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=a34da3225f7c4d50662dd6d5ea9383de&com=SHOW_ROMS&launID=693daf14ff92c7f6e9b5801f18fa4bb1) failed
20:06:06.288 T:1340   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'disks',)
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 42, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 271, in run_plugin
                                                self._command_render_roms(args['catID'][0], args['launID'][0])
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 3200, in _command_render_roms
                                                self._gui_render_rom_row(categoryID, launcherID, roms[key], key in roms_fav_set, False)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 3379, in _gui_render_rom_row
                                                if rom['disks']: AEL_MultiDisc_bool_value = AEL_MULTIDISC_BOOL_VALUE_TRUE
                                            KeyError: (u'disks',)
                                            -->End of Python script error report<--
20:06:06.317 T:2232   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=a34da3225f7c4d50662dd6d5ea9383de&com=SHOW_ROMS&launID=6bee77bd591d0a04d21bbf5fc92f961d
20:06:06.317 T:2232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=a34da3225f7c4d50662dd6d5ea9383de&com=SHOW_ROMS&launID=6bee77bd591d0a04d21bbf5fc92f961d) failed

**Comment by Wintermute0110** [comment]
You need to go to addon settings >> I/O tab >> Check/Update databases. It should work after that.

Also, please don't report issues in development version unless instructed to do so (for example, you report something in last released version, I do a patch and the ask you to test the development version). Development version can be very unstable sometimes...

I will close the issue now. Reopen if necessary.

**Comment by fx02** [comment]
Ok, sorry for reporting here. It works OK after DB update. Thank you.
