### ISSUE TITLE
[Feature request] Multiple rom locations

### ISSUE THREAD

**Issue by NihilisticEevee** [Wintermute0110/plugin.program.advanced.emulator.launcher#37]
Is it possible for you to add the ability to have multiple rom locations?
Thank you for your hard work and i love this addon!

**Comment by Wintermute0110** [comment]
Thanks. It may be done. Why do you need multiple ROM paths?

**Comment by fx02** [comment]
Well I for example have directory with ROMS that I currently play, and directory with all roms.

**Comment by NihilisticEevee** [comment]
Thank you.
I keep my roms in seperate folder depending on the set type, one for nointro, one for tosec, ect. it makes is really easy to update my sets with clrmame and scan them if they are in separate folders.

**Comment by Wintermute0110** [comment]
OK. Why not create separate launchers for No-Intro ROMs and TOSEC ROMs. If I add the multiple ROM path feature you will find multiple copies of the same ROM belonging to different sets. Additionally, if you want to use the AEL's NoIntro audit feature I think it's wise to keep NoIntro ROMs in their own launcher and other sets (Goodsets, TOSEC) in separate launchers. Otherwise you will have tons of missing ROMs if you audit your NoIntro set.

**Comment by NihilisticEevee** [comment]
sounds fine to me, i can set it up like that. I'd prefer to have all roms in one launcher but i can see how it would be harder and would kinda complicated the code base more than it needs to be. especially with the nointro audit feature. Thank you for your quick response and dedication to this fantastic plugin.

**Comment by Wintermute0110** [comment]
@NihilisticEevee Forgot to mention before... Suppose your have 3 ROM sets for SNES: NoIntro, TOSEC and Goodset. You organise your sets like this:

```
/home/kodi/AEL-ROMs/SNES/snes-nointro/
/home/kodi/AEL-ROMs/SNES/snes-tosec/
/home/kodi/AEL-ROMs/SNES/snes-goodset/
```

You can create a launcher and set the ROM path to `/home/kodi/AEL-ROMs/SNES`. If you activate the Recursive Scan option then ROMs in every subdirectory will be added to the launcher, which is what you want. Also, it is perfectly OK to create a different launcher with ROM path `/home/kodi/AEL-ROMs/SNES/snes-nointro` for your NoIntro set. In the NoIntro set you can use AEL's audit features using a NoIntro Parent/Clone XML DAT and use the Parent/Clone view mode.

**Comment by NihilisticEevee** [comment]
I didn't realize it have recursive scannering. This will work great, i will have to do a bit of reorganizing but it will work very well. Thank you so much! Thanks for the extra responce!
