### ISSUE TITLE
Feature request: “launch only once” feature

### ISSUE THREAD

**Issue by budtz** [Wintermute0110/plugin.program.advanced.emulator.launcher#39]
Any chance for a “launch only once” feature? So, if you DoubleClick only one instance of an application is launched. For kids or clumsy adults. Now several clicks or gamepad presses can open serval instances.

**Comment by Wintermute0110** [comment]
I'm a little bit lost... When you click on a runnable menu item (a standalone launcher or a ROM in a ROM launcher) the emulator/application is launcher on top of Kodi and you do not return to Kodi until the application is closed. Can you please elaborate more about the issue you have?

**Comment by budtz** [comment]
Thx for the reply

I returns just fine.

I use Retroarch. If I click on a runnable menu item it opens just fine. And I can close it again just fine and im back in kodi. What I mean is if I accidently click twice on the menu item in kodi. Then two instances are opened of Retroarch leading to a crash. 

So I’m suggesting a safeguard for user error or user clumsiness and not pointing out an actual error in the add-on.

**Comment by Wintermute0110** [comment]
Mmm... that could be very difficult to do. With Kodi API there is no way to know if another instance of AEL is running. I would need to create an additional service plugin that will monitor there is never 2 instances of AEL running. A lot of complexity for an error that only happens under very unusual circumstances.

**Comment by fx02** [comment]
Yeah, same "issues" here. Kids start game, then they forgot they started it and start again, and then cotrollers don't work as firs instance grabs controllers. But I know that's hard to fix even impossible :)

**Comment by Wintermute0110** [comment]
> Yeah, same "issues" here. Kids start game, then they forgot they started it and start again, and then cotrollers don't work as firs instance grabs controllers. But I know that's hard to fix even impossible :)

How they return to Kodi without closing the game? Do they use CTRL+TAB?

When I originally designed AEL I was thinking that the user will control Kodi with a gamepad and/or remote, never with a keyboard. With a gamepad is almost impossible to return to Kodi without closing the launched application...

**Comment by fx02** [comment]
We have HP MCE remote and I've assigned ALT+F4 on power button so whenever something goes wrong they close everything and just push the green MCE to start kodi again. Also ALT+F4 closes games and goes back to kodi.

**Comment by budtz** [comment]
Same here with kids and Remote. I will ad that pressing gamepad buttens while the launcher is launching is something kidds tend to do impatient as they are. Resulting in mutiple launches. But i thought also that this would be very hard to safeguard against.

**Comment by Wintermute0110** [comment]
OK, I understand now.

I will open a thread in the Kodi forum, addon developers subforum and ask the C++ core developers to add a new Python function to detect if several instances of AEL are running. That will enable solving this issue. By the way, this also will get rid *forever* of the database corruption issue. If core developers agree don't expect the fix anytime soon: at least it won't be working until Kodi Leia.

**Comment by budtz** [comment]
Thx. my problem isnt multiple instances of the addon opening but servaral instances of retroarch openening. but i know nothing of the technincal side so nice theres a chance for it to be fixed. i thought that there would be no way for ael to detect what is goin on with an extanal emulator so no way to prevent it from openening it twice.

**Comment by Wintermute0110** [comment]
Your are lucky. Apparently there is a solution that can be implemented in right away in Krypton (for the technicalities [have a look here](http://forum.kodi.tv/showthread.php?tid=310697). However, I'm currently very busy with real life. It's going to take a while until I code a fix. Also, this will get rid **forever** of any database corruptions issues in AEL. Finally, after so long!

**Comment by budtz** [comment]
Thats fantastic. And nice that this lead to a fix for database corruptions issues also!

**Comment by Wintermute0110** [comment]
Got a couple of hours and coded a fix for you. You need to install latest version from GitHub. Any problem you find I will need a debug log (have a look at AEL's thread for instructions).

**Comment by budtz** [comment]
Fantastic. Do I just redownload 0.9.6 beta 1 again?

**Comment by Wintermute0110** [comment]
No. You have to install a development version from GitHub. [Go here](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher) and follow the instructions at the bottom of the page "Installing the latest development version".

**Comment by Wintermute0110** [comment]
Please report if it works or not. If you have any trouble with the development version then roll back to `0.9.6-beta 1`.

**Comment by budtz** [comment]
I wrote in the forum. 

Yes it works great. Thx very much! My only issue is that the new error message that pops op if more instances of ael are running, takes the user out of the game. An option to disable the mesage would be great.

Venlig hilsen / Kind regards,
Jens Budtz-Jørgensen
 
Ekstern lektor; HA.Pro og HA.Alm ved CBS
 
INSTITUT FOR ORGANISATION
Kilen, Kilevej 14A, K4.91
2000 Frederiksberg
Denmark
 
Ekstern lektor; Master i Uddannelse og Læring ved RUC 
 
INSTITUT FOR PSYKOLOGI OG UDDANNELSESFORSKNING
Roskilde Universitet
Universitetsvej 1, DK-4000 Roskilde
 
Tel.: +45 51781835
jbu.ioa@cbs.dk; jbudtzj@ruc.dk

**Comment by Wintermute0110** [comment]
I will close the issue. The "launch only" problem has been solved... although it has some side effects. Open a new one if you find further problems please.
