### ISSUE TITLE
Add standalone, needs a launcher application?

### ISSUE THREAD

**Issue by efAston** [Wintermute0110/plugin.program.advanced.emulator.launcher#40]
Hi,

Sorry if I'm missing something, but when I try to add a standalone game, it comes up with a "Select launcher application" dialogue, and the only option is SuperRepo (a repository I installed earlier). Do I need to install something else before I can add standalone software with AEP?

Thanks in advance,
Aston
<img width="681" alt="selectlauncher" src="https://cloud.githubusercontent.com/assets/26708040/24348345/1c1205d6-1327-11e7-8734-c504f73490e4.png">

**Comment by Wintermute0110** [comment]
Maybe SuperRepo or some other *unofficial* addon you have installed has tampered with your Kodi installation and has modified your sources. Please check you [sources.xml file](http://kodi.wiki/view/sources.xml).

**Comment by efAston** [comment]
Thanks, I reinstalled Kodi and I can add the source now. The game launches in the background and Kodi turns into a black screen when the game launches, so I need to Alt+Tab to the game, and Kodi is still just a black screen after the game is closed, but the Add Source dialogue is fine now, it must have been that SuperRepo (which I only installed to try and install Advanced Launcher hahaha).

**Comment by Wintermute0110** [comment]
OK, good it worked. Keep in mind that currently the only supported way of installing AEL is from GitHub. In the future maybe AEL will be integrated in the *official* Kodi addon repository. Any other source or way of installing AEL is unofficial, not endorsed by my and won't be supported.

**Comment by efAston** [comment]
Good to know! It should be in the official repository, in fact it come with Kodi.

**Comment by efAston** [comment]
Success! It launches AND gets focus with the 17.1 update of Kodi. It closes back to the desktop rather than giving focus back to Kodi, but it's usable by remote control!

**Comment by Wintermute0110** [comment]
OK, good it worked.

I will close this issue since it seems to be solved. Feel free to reopen or open a new one if you find something else.
