### ISSUE TITLE
Submit to Official Kodi Repo?

### ISSUE THREAD

**Issue by RobLoach** [Wintermute0110/plugin.program.advanced.emulator.launcher#42]
Have any plans to submit this to the official Kodi repo?

**Comment by Wintermute0110** [comment]
Hi Rob,

Currently AEL is in heavy development and there is breakage between version. I think for now it's better to announce the new version on Kodi forum, users read the release notes and then manually install the ZIP.  If I include AEL in Kodi repository it will update automatically and then will stop working which may annoy some people.

Once AEL stabilises and reaches 1.0.0 I will include in Kodi repo.

**Comment by RobLoach** [comment]
Absolutely love the work you've done on this! Makes it super easy to add shortcuts and launch external applications. Thanks a lot, I'll close this for now. We can re-open when closer to a 1.0.0.
