### ISSUE TITLE
Error after scraper

### ISSUE THREAD

**Issue by SonOfFree** [Wintermute0110/plugin.program.advanced.emulator.launcher#51]
Hello,

it is the first time I use AEL, but I cannot get rid of this error. After scraping, I select the correct game (so it does find the game in the database) but then it gives the error below.

https://pastebin.com/E3CsQxPX

Let me know what it can be.

Davide

**Comment by Wintermute0110** [comment]
Thanks for reporting. Fixed. Please install development version from Github, try and close the issue if OK.
