### ISSUE TITLE
Can't use libretro with zipped .nes files

### ISSUE THREAD

**Issue by Lou-Cipher** [Wintermute0110/plugin.program.advanced.emulator.launcher#53]
I have my NES rom collection in zip files (one per rom), and I also have my NES launcher configured to accept "nes|zip" for extensions.  However, when I attempt to launch a rom using kodi's retroplayer, my only options are Hatari, FB Alpha, FB Alpha 2012, and Caprice32.  If I unzip the rom so it has an nes extension, then I get the usual slew of Nintendo emulators, and I can choose Nestopia.

**Comment by Lou-Cipher** [comment]
OK, so, digging through the code, it looks like the rom is just launched by calling
xbmc.Player().play(ROMFileName.getPath(), listitem)
At which point, it's Kodi returning a list of libretro addons it thinks are appropriate for the extension, yeah?  In which case, the problem is with kodi and this can be closed.  Gonna dig a bit more before I close the issue.

**Comment by Wintermute0110** [comment]
If we are talking about Retroplayer then yes, Retroplayer does not support zipped ROMs (TTBOMK at least for most of the cores... proper documentation is still missing).

The menu where you can choose the core to launch is shown by Kodi, not by AEL. I was talking with Garbear some time ago for a way for plugins to know which cores are installed and then the user can set in AEL his preference, but currently that is not possible.

**Comment by Lou-Cipher** [comment]
Gotcha, I'll close this out then and start digging through kodi's code.
