### ISSUE TITLE
duplicate label

### ISSUE THREAD

**Issue by Juxtaflows** [Wintermute0110/plugin.program.advanced.emulator.launcher#56]
in the file resources/settings.xml

section beginning line 67

`
    <setting id="separator" type="lsep" label="ROM tags"/>
    <setting label="Display ROM in Favourites tag" type="bool" id="display_rom_in_fav" default="true" />
    <setting label="Display ROM audit tag" type="bool" id="display_nointro_stat" default="true" />
    <setting label="Display ROM in Favourites tag" type="bool" id="display_fav_status" default="true" />
`

the label for line 70 (display_fav_status) is a duplicate of line 68 (display_rom_in_fav)
I propose updating the line 70 (display_fav_status) label for clarity.

display_fav_status only seems to add: (OK) to the rom title / description within 'favorites'
In the event the rom is no longer available, does (OK) change to alert the user?

**Comment by Wintermute0110** [comment]
Fixed in the release-0.9.8 branch. I will close the issue now.

Have a look at the [Favourites chapter](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/wiki/Getting-Started-Favourites) in AEL wiki for an explanation of the values of the `display_fav_status` tag.
