### ISSUE TITLE
Retroarch

### ISSUE THREAD

**Issue by Thrilleratplay** [Wintermute0110/plugin.program.advanced.emulator.launcher#61]
What is needed to reenable retroarch?

I was hoping to use this plugin with SPMC 17 on Android but cannot find a reason it was disabled.

**Comment by Wintermute0110** [comment]
What you mean by "enable Retroatch"? AEL is a general launcher and you should be able to launch any Android app with AEL. Can you please be more specific in your question?

**Comment by Thrilleratplay** [comment]
I was referring mainly to the comments in [this commit ](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/commit/667999b99ef0403526c107830f0ef490f901e3e3).  I should have made that clearer, sorry.  This commit gave me the impression that there are currently issues with using Retroarch or at least the preconfigured launcher option.

**Comment by Wintermute0110** [comment]
OK, I see. The stuff now in master contains a huge AEL refactoring. I merged some code by chrisism but didn't have time yet to properly look at it. Please ignore it from now. If you wish to have the latest AEL's features please get branch release-0.9.8 branch.

**Comment by Wintermute0110** [comment]
I will close the issue now. Please open a new issue if you find some other problem.
